export { default as About } from "./About";
export { default as Categories } from "./Categories";
export { default as Home } from "./Home";
export { default as Products } from "./Products";
export { default as Product } from "./Product";
export { default as Category } from "./Category";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Error } from "./Error";
